#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME             "Shelly"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME            "Shelly Plus i4"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.0.0"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION        0x00010000
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "2.0.0"
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION 2
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION_STRING "2.0.0"